server:
  port : 8081

spring:
  datasource:
    url: jdbc:h2:mem:user_db;NON_KEYWORDS=user
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers:true
        ddl-auto:update

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-user-device.html

